M.course=M.course||{};M.course.format=M.course.format||{};M.course.format.get_config=function(){return{container_node:'ul',container_class:'accordions',section_node:'li',section_class:'section'}}
M.course.format.swap_sections=function(Y,node1,node2){var CSS={COURSECONTENT:'course-content',SECTIONADDMENUS:'section_add_menus'};var sectionlist=Y.Node.all('.'+CSS.COURSECONTENT+' '+M.course.format.get_section_selector(Y));sectionlist.item(node1).one('.'+CSS.SECTIONADDMENUS).swap(sectionlist.item(node2).one('.'+CSS.SECTIONADDMENUS))}
M.course.format.process_sections=function(Y,sectionlist,response,sectionfrom,sectionto){var CSS={SECTIONNAME:'sectionname'},SELECTORS={SECTIONLEFTSIDE:'.left .section-handle img'};if(response.action=='move'){if(sectionfrom>sectionto){var temp=sectionto;sectionto=sectionfrom;sectionfrom=temp}
var ele,str,stridx,newstr;for(var i=sectionfrom;i<=sectionto;i++){sectionlist.item(i).one('.'+CSS.SECTIONNAME).setContent(response.sectiontitles[i]);ele=sectionlist.item(i).one(SELECTORS.SECTIONLEFTSIDE);str=ele.getAttribute('alt');stridx=str.lastIndexOf(' ');newstr=str.substr(0,stridx+1)+i;ele.setAttribute('alt',newstr);ele.setAttribute('title',newstr)}}};$(document).ready(function(){var $editing=!1;var hasnamedzero=$("#section-0").has(".content h3.sectionname").length;var $arrow;if(hasnamedzero){$arrow=$(".course-content ul.accordions li.section div.left.side, .course-content ul.accordions li.section div.right.side");$("#section-0 .summary, #section-0 .section").hide();$("#section-0 .side.right").show()}else{$arrow=$(".course-content ul.accordions li.section:not(:first-child) div.left.side, .course-content ul.accordions li.section:not(:first-child) div.right.side")}
$(".side.right").show();if($(":input[name=edit]").attr('value')==="off"){$editing=!0}
if($("body").hasClass('editing')){$editing=!0}
function openAll(){var allsections;if(hasnamedzero||$editing){allsections=$(".course-content ul.accordions ul.section, .course-content ul.accordions li.section .summary")}else{allsections=$(".course-content ul.accordions ul.section:not(:first), .course-content ul.accordions li.section:not(:first) .summary")}
$(".course-content ul.accordions ul.section, .course-content ul.accordions li.section .sectionname").addClass('active');allsections.slideDown('fast');if(!$editing){$arrow.removeClass('closed');$arrow.addClass('open')}}
function closeAll(){var allsections;if(hasnamedzero){allsections=$(".course-content ul.accordions ul.section, .course-content ul.accordions li.section .summary")}else{allsections=$(".course-content ul.accordions ul.section:not(:first), .course-content ul.accordions li.section:not(:first) .summary")}
$(".course-content ul.accordions ul.section, .course-content ul.accordions li.section .sectionname, .course-content ul.accordions li.section").removeClass('active');allsections.slideUp('fast');if(!$editing){$arrow.removeClass('open');$arrow.addClass('closed')}}
function toHex(str){var hex='';for(var i=0;i<str.length;i++){hex+=''+str.charCodeAt(i).toString(16)}
return hex}
var toggleAll="<a class='toggleopen'>Open</a> | <a class='toggleclose'>Close</a>";if(!hasnamedzero){$("#section-0").append(toggleAll)}
if($editing){openAll()}else{$arrow.addClass('closed')}
$("a.toggleopen").click(openAll);$("a.toggleclose").click(closeAll);var date=new Date();date.setTime(date.getTime()+(7*24*60*60*1000));var expires="; expires="+date.toGMTString();$(".section-title, .sectionname, div.left.side, div.right.side").click(function(){if(!$editing&&!$(this).closest(".section").find(".section, .summary").is(":visible")){closeAll();$(this).closest('li.section').toggleClass("active");$(this).closest(".section").find(".section, .summary").slideToggle("fast");$(this).closest("li.section.main").find("div.left.side, div.right.side").toggleClass("open closed");document.cookie="course"+toHex(document.location.search)+"="+$(this).closest("li.section.main").attr('id')+expires+"; path=/"}});if(!$editing){var ca=document.cookie.split(';');var nameEQ="course"+toHex(document.location.search)+"=";var opensection='section-1';for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1,c.length)}
if(c.indexOf(nameEQ)==0){opensection='#'+c.substring(nameEQ.length,c.length)}}
$(opensection+" .section").show();$(opensection+" .summary").show();$(opensection+" .sectionname").addClass('active');$(opensection+" div.left.side, "+opensection+" div.right.side").removeClass('closed');$(opensection+" div.left.side, "+opensection+" div.right.side").addClass('open')}})