require(['jquery','jqueryui','theme_engage/jquery.smartbanner'],function($){$(document).ready(function(){$('#page-mod-assign-view a.tooltip').tooltip();$('.showtooltip').tooltip({position:{my:"left+10 top",at:"right top"}});if(window.location.href.match('local/mail')){show_smartbanner()}
$('a.editing_mark_important').click(function(event){event.preventDefault();var link=$(this);var href=link.attr('href')+'&json=1';$.get(href,function(data){var img=$(link.children('img')[0]);img.attr('src',data)})});var modalWidth=$(window).width()*0.7;$(".dialog").dialog({autoOpen:!1,closeOnEscape:!0,dialogClass:"grade_content",draggable:!0,maxHeight:$(window).height()*.9,minWidth:modalWidth,modal:!0,resizeable:!0});$('.open_grade_content').click(function(event){event.preventDefault();var id=$(this).data('id');var dom_id="#extra_grading_content_"+id;$(dom_id).dialog("open")});addEngageVideoEvents('video');$.each($('[id^=inst]'),function(index,value){var id=$(value).attr('id');if(/inst[0-9]+/.test(id)){if(getCookie(id)=='close'){$("#"+id+"-body").addClass('collapsed');$("#"+id+"-block-toggle").html('+')}}});$('.block-toggle').click(function(event){event.preventDefault();var id=$(this).data('id');if(getCookie(id)=='close'){open_block(id);$(this).html('-')}else{close_block(id);$(this).html('+')}})});function show_smartbanner(){$.smartbanner({title:'Engage | LINK',author:'Wiley',price:'Free',inGooglePlay:'Check Engage mail, course announcements and grades',GooglePlayParams:null,icon:M.util.image_url('ic_engage_logo','theme_engage'),url:null,button:'VIEW',scale:'auto',speedIn:300,speedOut:400,daysHidden:15,daysReminder:90,force:null,hideOnInstall:!0,layer:!1,appendToSelector:'header.navbar',onInstall:function(){},onClose:function(){}});$('#smartbanner').css('position','relative')}
function handleEngageVideoCaptions(player_selector,video_uuid){}
function getCookie(cname){var name=cname+"=";var decodedCookie=decodeURIComponent(document.cookie);var ca=decodedCookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1)}
if(c.indexOf(name)==0){return c.substring(name.length,c.length)}}
return""}
function close_block(id){$("#"+id+"-body").addClass('collapsed');document.cookie=id+"=close; path=/"}
function open_block(id){$("#"+id+"-body").removeClass('collapsed');document.cookie=id+"=open; path=/"}});function addNavDrawerEvents(){$('body').on('webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend',function(e){if(e.target==this){if($(this).hasClass('drawer-open-left')||$(this).hasClass('drawer-open-right')){$(this).trigger('nav-drawer-opened')}else{$(this).trigger('nav-drawer-closed')}}})}
function addEngageVideoEvents(selector){$(selector).on('play',function(e){trackVideoEvent('video-play',this)});$(selector).on('pause',function(e){trackVideoEvent('video-pause',this)});$(selector).on('seeking',function(e){trackVideoEvent('video-seeking',this)});$(selector).on('ended',function(e){trackVideoEvent('video-ended',this)})}
function trackVideoEvent(eventName,video){var uuid=$(video).data('uuid');var title=$(video).data('title');var currentTime=$(video)[0].currentTime;var duration=$(video)[0].duration;var path=$(video).data('path');var classes=$('body').attr('class');var context_match=/context-(\d+)/i;var matches=context_match.exec(classes);if(matches){var contextid=matches[1]}else{var contextid=null}
var course_match=/course-(\d+)/i;matches=course_match.exec(classes);if(matches){var courseid=matches[1]}else{var courseid=null}
var cmid_match=/cmid-(\d+)/i;matches=cmid_match.exec(classes);if(matches){var cmid=matches[1]}else{var cmid=null}
var category_match=/category-(\d+)/i;matches=category_match.exec(classes);if(matches){var categoryid=matches[1]}else{var categoryid=null}
$.get(M.cfg.wwwroot+'/local/engage_video/event.php',{'contextid':contextid,'courseid':courseid,'cmid':cmid,'categoryid':categoryid,'event':eventName,'uuid':uuid,'title':title,'currentTime':currentTime,'duration':duration,'path':path})};
require(['jquery','jqueryui'],function($){function convert_playlists(selector){var playlists=$(selector);$.each(playlists,function(index,playlist){var playlist_type='dynamic';if($(playlist).hasClass('horizontal')){playlist_type='horizontal'}else if($(playlist).hasClass('vertical')){playlist_type='vertical'}
var video_list_selector='video-list-'+index;var video_player_selector='video-player-'+index;var container=$('<div class="ev-playlist-container '+playlist_type+'" id="playlist-container-'+index+'"></div>');var player_wrapper=$('<div class="ev-aspect-wrapper"><div class="aspect-ratio aspect-ratio-16-9"><video crossOrigin="anonymous" class="ev-video" id="'+video_player_selector+'" data-title="" data-uuid="" controls><source src="notreal.mp4" type="video/mp4"></video></div></div>');var player=player_wrapper.find('video');var videos_list=$('<ul class="ev-video-list" id="'+video_list_selector+'"></ul>');var videos=$(playlist).find('li a');$.each(videos,function(index,video){var video_url=$(video).data('url');var video_uuid=$(video).data('uuid');var video_title=$(video).data('title');var video_poster=$(video).data('poster');var video_captions_url=$(video).data('captions');if(index==0){$(player).data('uuid',video_uuid);$(player).data('title',video_title);player.attr('poster',video_poster);player.find('source')[0].src=video_url;$(player[0]).children('track').remove();if(video_captions_url){var captions=$('<track kind="subtitles" label="English captions" src="'+video_captions_url+'" srclang="en" default>');$(player).append(captions)}
player.get(0).load()}
videos_list.append('<li><a data-uuid="'+video_uuid+'" data-title="'+video_title+'" data-captions="'+video_captions_url+'" href="'+video_url+'"><img src="'+video_poster+'"><div class="ev-caption">'+video_title+'</div></a></li>')});container.append(player_wrapper);container.append(videos_list);$(playlist).before(container);$(playlist).remove();set_video_click_handlers('#'+video_list_selector+' li','#'+video_player_selector);if(playlist_type=='dynamic'||playlist_type=='vertical'){$(window).resize(function(){setListHeight('#'+video_player_selector,'#'+video_list_selector)});$(window).scroll(function(){setListHeight('#'+video_player_selector,'#'+video_list_selector)});$(window).on('load',function(){setListHeight('#'+video_player_selector,'#'+video_list_selector)});setListHeight('#'+video_player_selector,'#'+video_list_selector)}
if(typeof addEngageVideoEvents=='function'){addEngageVideoEvents('#'+video_player_selector)}})}
function setListHeight(video_player_selector,video_list_selector){var player=$(video_player_selector);$(video_list_selector).css('max-height',player.height())}
function set_video_click_handlers(list_selector,player_selector){$(list_selector).on('click',function(event){event.preventDefault();var player=$(player_selector);var video=$(this).find('a');var video_uuid=video.data('uuid');var video_captions_url=video.data('captions');player.data('uuid',video_uuid);player.data('title',video.data('title'));player.data('poster',video.data('poster'));player.find('source')[0].src=video.attr('href');$(player[0]).children('track').remove();if(video_captions_url){var captions=$('<track kind="subtitles" label="English captions" src="'+video_captions_url+'" srclang="en" default>');$(player).append(captions)}
player.get(0).load();player.get(0).play()})}
$(document).ready(function(){convert_playlists('ul.ev-playlist')})});
require(['jquery','jqueryui','theme_engage/elasticsearch.jquery'],function($,jqui){jQuery.ajaxPrefilter(function(options,originalOptions,jqXHR){options.cache=!1});$("#page-mod-page-view #support-page-tabs").tabs({beforeLoad:function(event,ui){ui.jqXHR.fail(function(){ui.panel.html("Could not load this tab. Please contact the Personal Support Center using the contact information at the bottom of this page.")})}})})